### ISSUE TITLE
Hackage Release 0.6.1 does not compile with GHC 8.6.5

### ISSUE THREAD

**Issue by fendor** [andrewthad/contiguous#45]
```sh
> cabal get contiguous-0.6.1
> cd contiguous-0.6.1
> cabal build -w ghc-8.6.5
...
src/Data/Primitive/Contiguous/Class.hs:11:14: error:
    Unsupported extension: UnliftedNewtypes
    Perhaps you meant ‘UnliftedFFITypes’
   |
11 | {-# LANGUAGE UnliftedNewtypes #-}
   |              ^^^^^^^^^^^^^
```

As master has a lower bound of GHC 8.10, I guess this is mostly an oversight of updating bounds for the Hackage Release.

**Comment by andrewthad** [comment]
I've bumped the lower bound for base to 4.14 in a hackage revision to resolve this. Closing.
